# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/telemetry_schema.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'proto/telemetry_schema.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cproto/telemetry_schema.proto\x12\x19\x61utoroboticarms.telemetry\"J\n\rArmKinematics\x12\x10\n\x08\x62\x61se_deg\x18\x01 \x01(\x02\x12\x14\n\x0cshoulder_deg\x18\x02 \x01(\x02\x12\x11\n\telbow_deg\x18\x03 \x01(\x02\"\x84\x02\n\x11TelemetrySnapshot\x12\x16\n\x0eschema_version\x18\x01 \x01(\r\x12\x11\n\ttimestamp\x18\x02 \x01(\x01\x12\x14\n\x0csystem_state\x18\x03 \x01(\t\x12\x13\n\x0bwatchdog_ms\x18\x04 \x01(\r\x12:\n\x08left_arm\x18\x05 \x01(\x0b\x32(.autoroboticarms.telemetry.ArmKinematics\x12;\n\tright_arm\x18\x06 \x01(\x0b\x32(.autoroboticarms.telemetry.ArmKinematicsJ\x04\x08\x07\x10\x08J\x04\x08\x08\x10\tR\x14old_diagnostic_bytesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.telemetry_schema_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARMKINEMATICS']._serialized_start=59
  _globals['_ARMKINEMATICS']._serialized_end=133
  _globals['_TELEMETRYSNAPSHOT']._serialized_start=136
  _globals['_TELEMETRYSNAPSHOT']._serialized_end=396
# @@protoc_insertion_point(module_scope)
